EXTRAFLAGS += -flto
RGBLIGHT_ENABLE = yes
RGBLIGHT_SPLIT = yes
RGBLIGHT_DEFAULT_MODE = RGBLIGHT_MODE_BREATHING0
RGBLIGHT_DEFAULT_HUE = 190
RGBLIGHT_DEFAULT_SAT = 255
RGBLIGHT_DEFAULT_VAL = RGBLIGHT_LIMIT_VAL
RGBLIGHT_DEFAULT_SPD = 0
